;;;; matrices.lisp
;;;; Minimal column-major 4x4 matrix module (replaces 3d-matrices)
;;;;
;;;; Internally matrices are always column-major with column-vector math
;;;; (M*v). *matrix-layout* controls only the flat array serialization
;;;; format used by MARR / MAT4-FROM-ARRAY, so users targeting a
;;;; row-major pipeline (e.g. WebGPU/WGSL) can emit/read the transposed
;;;; layout without any change to the internal math.

(defpackage #:cl-meshgen.mat
  (:use #:cl #:cl-meshgen.vec)
  (:export #:mat4 #:mat4-p
           #:mtranslation #:mscaling #:mrotation
           #:m* #:mtranspose #:minv
           #:*matrix-layout* #:marr #:mat4-from-array))

(in-package #:cl-meshgen.mat)

(declaim (inline sf))
(defun sf (x)
  (coerce x 'single-float))

(defstruct (mat4 (:constructor %make-mat4 (data)))
  (data nil :type (simple-array single-float (16))))

;; Storage index for row R, col C (column-major): C*4 + R.
(declaim (inline idx))
(defun idx (r c)
  (+ (* c 4) r))

(defun mref (m r c)
  (aref (mat4-data m) (idx r c)))

(defun (setf mref) (value m r c)
  (setf (aref (mat4-data m) (idx r c)) value))

(defun meye ()
  (let ((m (%make-mat4 (make-array 16 :element-type 'single-float :initial-element 0.0))))
    (setf (mref m 0 0) 1.0
          (mref m 1 1) 1.0
          (mref m 2 2) 1.0
          (mref m 3 3) 1.0)
    m))

(defun mtranslation (v)
  (let ((m (meye)))
    (setf (mref m 0 3) (vx3 v)
          (mref m 1 3) (vy3 v)
          (mref m 2 3) (vz3 v))
    m))

(defun mscaling (v)
  (let ((m (meye)))
    (setf (mref m 0 0) (vx3 v)
          (mref m 1 1) (vy3 v)
          (mref m 2 2) (vz3 v))
    m))

(defun mrotation (axis angle)
  "Axis-angle (Rodrigues) rotation matrix. AXIS need not be normalized."
  (let* ((n (vunit axis))
         (x (vx3 n)) (y (vy3 n)) (z (vz3 n))
         (angle (sf angle))
         (c (cos angle)) (s (sin angle)) (omc (- 1.0 c))
         (m (meye)))
    (setf (mref m 0 0) (+ c (* x x omc))
          (mref m 0 1) (- (* x y omc) (* z s))
          (mref m 0 2) (+ (* x z omc) (* y s))
          (mref m 1 0) (+ (* y x omc) (* z s))
          (mref m 1 1) (+ c (* y y omc))
          (mref m 1 2) (- (* y z omc) (* x s))
          (mref m 2 0) (- (* z x omc) (* y s))
          (mref m 2 1) (+ (* z y omc) (* x s))
          (mref m 2 2) (+ c (* z z omc)))
    m))

(defun m*-mat (a b)
  (let ((out (%make-mat4 (make-array 16 :element-type 'single-float :initial-element 0.0))))
    (dotimes (r 4)
      (dotimes (c 4)
        (setf (mref out r c)
              (loop for k below 4 sum (* (mref a r k) (mref b k c))))))
    out))

(defun m*-vec (m v)
  (let ((x (vx3 v)) (y (vy3 v)) (z (vz3 v)))
    (vec3 (+ (* (mref m 0 0) x) (* (mref m 0 1) y) (* (mref m 0 2) z) (mref m 0 3))
          (+ (* (mref m 1 0) x) (* (mref m 1 1) y) (* (mref m 1 2) z) (mref m 1 3))
          (+ (* (mref m 2 0) x) (* (mref m 2 1) y) (* (mref m 2 2) z) (mref m 2 3)))))

(defun m* (a b)
  (typecase b
    (mat4 (m*-mat a b))
    (vec3 (m*-vec a b))
    (t (error "M*: unsupported second operand ~S" b))))

(defun mtranspose (m)
  (let ((out (%make-mat4 (make-array 16 :element-type 'single-float :initial-element 0.0))))
    (dotimes (r 4)
      (dotimes (c 4)
        (setf (mref out r c) (mref m c r))))
    out))

(defun minv (m)
  "General 4x4 matrix inverse via cofactor/adjugate. Signals an error if M is singular."
  (let* ((a (mat4-data m))
         (inv (make-array 16 :element-type 'single-float :initial-element 0.0)))
    (macrolet ((e (i) `(aref a ,i)))
      (setf (aref inv 0)
            (+ (- (* (e 5) (e 10) (e 15)))
               (* (e 5) (e 11) (e 14))
               (* (e 9) (e 6) (e 15))
               (- (* (e 9) (e 7) (e 14)))
               (- (* (e 13) (e 6) (e 11)))
               (* (e 13) (e 7) (e 10)))
            (aref inv 4)
            (+ (* (e 4) (e 10) (e 15))
               (- (* (e 4) (e 11) (e 14)))
               (- (* (e 8) (e 6) (e 15)))
               (* (e 8) (e 7) (e 14))
               (* (e 12) (e 6) (e 11))
               (- (* (e 12) (e 7) (e 10))))
            (aref inv 8)
            (+ (- (* (e 4) (e 9) (e 15)))
               (* (e 4) (e 11) (e 13))
               (* (e 8) (e 5) (e 15))
               (- (* (e 8) (e 7) (e 13)))
               (- (* (e 12) (e 5) (e 11)))
               (* (e 12) (e 7) (e 9)))
            (aref inv 12)
            (+ (* (e 4) (e 9) (e 14))
               (- (* (e 4) (e 10) (e 13)))
               (- (* (e 8) (e 5) (e 14)))
               (* (e 8) (e 6) (e 13))
               (* (e 12) (e 5) (e 10))
               (- (* (e 12) (e 6) (e 9))))
            (aref inv 1)
            (+ (* (e 1) (e 10) (e 15))
               (- (* (e 1) (e 11) (e 14)))
               (- (* (e 9) (e 2) (e 15)))
               (* (e 9) (e 3) (e 14))
               (* (e 13) (e 2) (e 11))
               (- (* (e 13) (e 3) (e 10))))
            (aref inv 5)
            (+ (- (* (e 0) (e 10) (e 15)))
               (* (e 0) (e 11) (e 14))
               (* (e 8) (e 2) (e 15))
               (- (* (e 8) (e 3) (e 14)))
               (- (* (e 12) (e 2) (e 11)))
               (* (e 12) (e 3) (e 10)))
            (aref inv 9)
            (+ (* (e 0) (e 9) (e 15))
               (- (* (e 0) (e 11) (e 13)))
               (- (* (e 8) (e 1) (e 15)))
               (* (e 8) (e 3) (e 13))
               (* (e 12) (e 1) (e 11))
               (- (* (e 12) (e 3) (e 9))))
            (aref inv 13)
            (+ (- (* (e 0) (e 9) (e 14)))
               (* (e 0) (e 10) (e 13))
               (* (e 8) (e 1) (e 14))
               (- (* (e 8) (e 2) (e 13)))
               (- (* (e 12) (e 1) (e 10)))
               (* (e 12) (e 2) (e 9)))
            (aref inv 2)
            (+ (- (* (e 1) (e 6) (e 15)))
               (* (e 1) (e 7) (e 14))
               (* (e 5) (e 2) (e 15))
               (- (* (e 5) (e 3) (e 14)))
               (- (* (e 13) (e 2) (e 7)))
               (* (e 13) (e 3) (e 6)))
            (aref inv 6)
            (+ (* (e 0) (e 6) (e 15))
               (- (* (e 0) (e 7) (e 14)))
               (- (* (e 4) (e 2) (e 15)))
               (* (e 4) (e 3) (e 14))
               (* (e 12) (e 2) (e 7))
               (- (* (e 12) (e 3) (e 6))))
            (aref inv 10)
            (+ (- (* (e 0) (e 5) (e 15)))
               (* (e 0) (e 7) (e 13))
               (* (e 4) (e 1) (e 15))
               (- (* (e 4) (e 3) (e 13)))
               (- (* (e 12) (e 1) (e 7)))
               (* (e 12) (e 3) (e 5)))
            (aref inv 14)
            (+ (* (e 0) (e 5) (e 14))
               (- (* (e 0) (e 6) (e 13)))
               (- (* (e 4) (e 1) (e 14)))
               (* (e 4) (e 2) (e 13))
               (* (e 12) (e 1) (e 6))
               (- (* (e 12) (e 2) (e 5))))
            (aref inv 3)
            (+ (* (e 1) (e 6) (e 11))
               (- (* (e 1) (e 7) (e 10)))
               (- (* (e 5) (e 2) (e 11)))
               (* (e 5) (e 3) (e 10))
               (* (e 9) (e 2) (e 7))
               (- (* (e 9) (e 3) (e 6))))
            (aref inv 7)
            (+ (- (* (e 0) (e 6) (e 11)))
               (* (e 0) (e 7) (e 10))
               (* (e 4) (e 2) (e 11))
               (- (* (e 4) (e 3) (e 10)))
               (- (* (e 8) (e 2) (e 7)))
               (* (e 8) (e 3) (e 6)))
            (aref inv 11)
            (+ (* (e 0) (e 5) (e 11))
               (- (* (e 0) (e 7) (e 9)))
               (- (* (e 4) (e 1) (e 11)))
               (* (e 4) (e 3) (e 9))
               (* (e 8) (e 1) (e 7))
               (- (* (e 8) (e 3) (e 5))))
            (aref inv 15)
            (+ (- (* (e 0) (e 5) (e 10)))
               (* (e 0) (e 6) (e 9))
               (* (e 4) (e 1) (e 10))
               (- (* (e 4) (e 2) (e 9)))
               (- (* (e 8) (e 1) (e 6)))
               (* (e 8) (e 2) (e 5))))
      (let ((det (+ (* (e 0) (aref inv 0))
                    (* (e 1) (aref inv 4))
                    (* (e 2) (aref inv 8))
                    (* (e 3) (aref inv 12)))))
        (when (zerop det)
          (error "MINV: matrix is singular"))
        (let ((inv-det (/ 1.0 det)))
          (dotimes (i 16)
            (setf (aref inv i) (* (aref inv i) inv-det))))))
    (%make-mat4 inv)))

(defparameter *matrix-layout* :column-major
  "Serialization layout for MARR / MAT4-FROM-ARRAY: :COLUMN-MAJOR (default,
matches column-vector math, e.g. OpenGL) or :ROW-MAJOR (e.g. WebGPU/WGSL).
Internal math is always column-major with column vectors; this only
controls how the flat 16-float array is emitted/read.")

(defun marr (m &optional (layout *matrix-layout*))
  (ecase layout
    (:column-major (copy-seq (mat4-data m)))
    (:row-major (mat4-data (mtranspose m)))))

(defun mat4-from-array (arr &optional (layout *matrix-layout*))
  (let ((data (make-array 16 :element-type 'single-float
                              :initial-contents (map 'list #'sf arr))))
    (ecase layout
      (:column-major (%make-mat4 data))
      (:row-major (mtranspose (%make-mat4 data))))))
