;;;; tests.lisp
;;;; Test suite for common-shapes – using ASDF‑relative paths

(defpackage #:common-shapes/test
  (:use #:cl #:common-shapes #:fiveam)
  (:export #:run-tests))
(in-package #:common-shapes/test)

;;;; Path handling – write OBJ files to a subdirectory of the system

(defun output-path (name &optional suffix)
  "Return a pathname for an OBJ file in the test output directory.
NAME   – a symbol or string, used as the base filename.
SUFFIX – optional string added before the extension (e.g. \"full\")."
  (let* ((base (asdf:system-relative-pathname
                :common-shapes "test/"))
         (dir  (ensure-directories-exist base))
         (file (format nil "~(~A~)~@[-~A~].obj" name suffix)))
    (merge-pathnames file dir)))

;;;; OBJ Writer (unchanged)

(defun write-mesh-to-obj (mesh filepath)
  (let* ((vertices   (mesh-vertices mesh))
         (indices    (mesh-indices mesh))
         (normals    (mesh-normals mesh))
         (tex-coords (mesh-tex-coords mesh))
         (dims       (mesh-dimensions mesh))
         (v-count    (vertex-count mesh))
         (t-count    (triangle-count mesh))
         (has-n      (not (null normals)))
         (has-uv     (not (null tex-coords))))
    (ensure-directories-exist filepath)
    (with-open-file (out filepath :direction :output
                                  :if-exists :supersede
                                  :if-does-not-exist :create)
      (format out "# Generated by common-shapes~%# Vertices: ~D  Triangles: ~D~%~%" v-count t-count)
      ;; Vertex positions — always emit 3 components (z=0.0 for 2D)
      (dotimes (i v-count)
        (if (= dims 3)
            (let ((b (* i 3)))
              (format out "v ~,6F ~,6F ~,6F~%" (aref vertices b) (aref vertices (+ b 1)) (aref vertices (+ b 2))))
            (let ((b (* i 2)))
              (format out "v ~,6F ~,6F 0.000000~%" (aref vertices b) (aref vertices (+ b 1))))))
      ;; Texture coordinates
      (when has-uv
        (dotimes (i v-count)
          (let ((b (* i 2)))
            (format out "vt ~,6F ~,6F~%" (aref tex-coords b) (aref tex-coords (+ b 1))))))
      ;; Normals
      (when has-n
        (dotimes (i v-count)
          (let ((b (* i 3)))
            (format out "vn ~,6F ~,6F ~,6F~%" (aref normals b) (aref normals (+ b 1)) (aref normals (+ b 2))))))
      ;; Faces (1-indexed)
      (dotimes (tri t-count)
        (let* ((b  (* tri 3))
               (i0 (1+ (aref indices b)))
               (i1 (1+ (aref indices (+ b 1))))
               (i2 (1+ (aref indices (+ b 2)))))
          (cond
            ((and has-uv has-n)
             (format out "f ~D/~D/~D ~D/~D/~D ~D/~D/~D~%" i0 i0 i0 i1 i1 i1 i2 i2 i2))
            (has-uv
             (format out "f ~D/~D ~D/~D ~D/~D~%" i0 i0 i1 i1 i2 i2))
            (has-n
             (format out "f ~D//~D ~D//~D ~D//~D~%" i0 i0 i1 i1 i2 i2))
            (t
             (format out "f ~D ~D ~D~%" i0 i1 i2))))))
    t))

;;;; Sanity helper (unchanged)

(defun check-mesh (mesh &key normals tex-coords)
  (and (not (null (mesh-vertices mesh)))
       (not (null (mesh-indices mesh)))
       (> (vertex-count mesh) 0)
       (> (triangle-count mesh) 0)
       (if normals    (not (null (mesh-normals mesh)))    t)
       (if tex-coords (not (null (mesh-tex-coords mesh))) t)))

;;;; Macro to generate the repetitive shape tests

(defmacro define-shape-test (name (constructor &rest base-args)
                             &key
                             (base-checks nil)
                             (extra-variants nil))
  "Define a FiveAM test for a shape constructor.
NAME         – symbol naming the test (also used to build output filenames)
CONSTRUCTOR  – function that creates the mesh (e.g. make-rectangle-2d)
BASE-ARGS    – required arguments for the constructor (without keyword options)
BASE-CHECKS  – list of assertions to run on the basic mesh (e.g. ((= 4 (vertex-count mesh))))
EXTRA-VARIANTS – list of additional variants, each of the form
                 (SUFFIX EXTRA-ARGS EXTRA-CHECKS)
                 where EXTRA-ARGS are keyword arguments added to the constructor
                 and EXTRA-CHECKS are assertions specific to that variant.
The macro automatically adds:
- a basic variant (no normals/tex-coords)
- a full variant (:normals t :tex-coords t)
plus any user-supplied extra variants."
  (let ((basic-test
          `(let ((mesh (,constructor ,@base-args)))
             (is (check-mesh mesh))
             ,@(loop for check in base-checks collect `(is ,check))
             (is (write-mesh-to-obj mesh (output-path ',name)))))
        (full-test
          `(let ((mesh (,constructor ,@base-args :normals t :tex-coords t)))
             (is (check-mesh mesh :normals t :tex-coords t))
             (is (write-mesh-to-obj mesh (output-path ',name "full")))))
        (extra-forms
          (loop for (suffix extra-args extra-checks) in extra-variants
                collect
                `(let ((mesh (,constructor ,@base-args ,@extra-args)))
                   (is (check-mesh mesh
                                    ,@(when (find :normals extra-args) '(:normals t))
                                    ,@(when (find :tex-coords extra-args) '(:tex-coords t))))
                   ,@(loop for check in extra-checks collect `(is ,check))
                   (is (write-mesh-to-obj mesh (output-path ',name ,suffix)))))))
    `(test ,name
       ,basic-test
       ,full-test
       ,@extra-forms)))

;;;; Test suites

(def-suite common-shapes-suite
  :description "All common-shapes tests")

(def-suite* shapes-2d :in common-shapes-suite)

(define-shape-test rectangle-2d (make-rectangle-2d 2.0 1.0)
  :base-checks ((= 4 (vertex-count mesh))
                (= 2 (triangle-count mesh))))

(define-shape-test circle-2d (make-circle-2d 1.0 32))

(define-shape-test polygon-2d (make-polygon-2d 6 1.0)
  :base-checks ((= 7 (vertex-count mesh))
                (= 6 (triangle-count mesh))))

(define-shape-test ellipse-2d (make-ellipse-2d 2.0 1.0 32)
  :extra-variants (("3d" (:3d t) ((= 3 (mesh-dimensions mesh))))))

(def-suite* shapes-3d :in common-shapes-suite)

(define-shape-test cube (make-cube 1.0)
  :base-checks ((= 24 (vertex-count mesh))
                (= 12 (triangle-count mesh))))

(define-shape-test box (make-box 2.0 1.0 0.5))

(define-shape-test sphere (make-sphere 1.0 16 16))

(define-shape-test icosphere (make-icosphere 1.0 2))

(define-shape-test cylinder (make-cylinder 0.5 1.0 16 4))

(define-shape-test cone (make-cone 0.5 1.0 16 4))

(define-shape-test torus (make-torus 1.0 0.3 16 16))

(define-shape-test plane (make-plane 2.0 2.0 4 4))

(define-shape-test hemisphere (make-hemisphere 1.0 16 8))

(define-shape-test capsule (make-capsule 0.5 1.0 16 8))

;; merge-arrow is special – keep it explicit
(test merge-arrow
  ;; Shaft: cylinder centered at origin, translated up so base is at y=0, tip at y=1.5
  ;; Head:  cone with base at y=0, apex at y=0.5, translated up to sit at y=1.5
  (let* ((shaft (translate-mesh (make-cylinder 0.3 1.5 16 4) 0 0.75 0))
         (head  (translate-mesh (make-cone    0.6 0.5 16 1) 0 1.5  0))
         (arrow (merge-meshes shaft head)))
    (is (check-mesh arrow))
    (is (= (+ (vertex-count shaft) (vertex-count head))
           (vertex-count arrow)))
    (is (= (+ (triangle-count shaft) (triangle-count head))
           (triangle-count arrow)))
    (is (write-mesh-to-obj arrow (output-path 'arrow))))
  ;; Same with normals — merge only preserves them when both parts have them
  (let* ((shaft (translate-mesh (make-cylinder 0.3 1.5 16 4 :normals t) 0 0.75 0))
         (head  (translate-mesh (make-cone    0.6 0.5 16 1 :normals t) 0 1.5  0))
         (arrow (merge-meshes shaft head)))
    (is (check-mesh arrow :normals t))
    (is (write-mesh-to-obj arrow (output-path 'arrow "normals")))))

(def-suite* shapes-platonic :in common-shapes-suite)

(define-shape-test tetrahedron (make-tetrahedron 1.0)
  :base-checks ((= 12 (vertex-count mesh))
                (= 4 (triangle-count mesh))))

(define-shape-test octahedron (make-octahedron 1.0)
  :base-checks ((= 24 (vertex-count mesh))
                (= 8 (triangle-count mesh))))

(define-shape-test icosahedron (make-icosahedron 1.0)
  :base-checks ((= 60 (vertex-count mesh))
                (= 20 (triangle-count mesh))))

(define-shape-test dodecahedron (make-dodecahedron 1.0)
  :base-checks ((= 108 (vertex-count mesh))
                (= 36 (triangle-count mesh))))

;;;; Entrypoint

(def-suite* csg :in common-shapes-suite)

(test csg-union-test
  (let* ((a (make-cube 1.0))
         (b (translate-mesh (make-cube 1.0) 0.5 0.0 0.0))
         (result (csg-union a b)))
    (is (check-mesh result))
    (is (= 3 (mesh-dimensions result)))
    (is (write-mesh-to-obj result (output-path 'csg-union)))))

(test csg-intersection-test
  (let* ((a (make-cube 1.0))
         (b (translate-mesh (make-cube 1.0) 0.5 0.0 0.0))
         (result (csg-intersection a b)))
    (is (check-mesh result))
    (is (= 3 (mesh-dimensions result)))
    (is (write-mesh-to-obj result (output-path 'csg-intersection)))))

(test csg-difference-test
  (let* ((a (make-cube 1.0))
         (b (translate-mesh (make-cube 1.0) 0.5 0.0 0.0))
         (result (csg-difference a b)))
    (is (check-mesh result))
    (is (= 3 (mesh-dimensions result)))
    (is (write-mesh-to-obj result (output-path 'csg-difference)))))

(test csg-sphere-intersection
  (let* ((a (make-sphere 1.0 16 12))
         (b (translate-mesh (make-sphere 1.0 16 12) 0.5 0.0 0.0))
         (result (csg-intersection a b)))
    (is (check-mesh result))
    (is (write-mesh-to-obj result (output-path 'csg-sphere-intersection)))))

(test csg-cylinder-difference
  (let* ((a (make-cube 2.0))
         (b (make-cylinder 0.5 2.0 16 4))
         (result (csg-difference a b)))
    (is (check-mesh result))
    (is (write-mesh-to-obj result (output-path 'csg-cylinder-difference)))))

(defun run-tests ()
  (run! 'common-shapes-suite))
