;;;; tests.lisp
;;;; Test suite for common-shapes – using ASDF‑relative paths

(defpackage #:common-shapes/test
  (:use #:cl #:common-shapes #:fiveam)
  (:local-nicknames (:v #:common-shapes.vec)
                    (:m #:common-shapes.mat))
  (:export #:run-tests))
(in-package #:common-shapes/test)

;;;; Path handling – write OBJ files to a subdirectory of the system

(defun output-path (name &optional suffix)
  "Return a pathname for an OBJ file in the test output directory.
NAME   – a symbol or string, used as the base filename.
SUFFIX – optional string added before the extension (e.g. \"full\")."
  (let* ((base (asdf:system-relative-pathname
                :common-shapes "test/"))
         (dir  (ensure-directories-exist base))
         (file (format nil "~(~A~)~@[-~A~].obj" name suffix)))
    (merge-pathnames file dir)))

;;;; OBJ Writer (unchanged)

(defun write-mesh-to-obj (mesh filepath)
  (let* ((vertices   (mesh-vertices mesh))
         (indices    (mesh-indices mesh))
         (normals    (mesh-normals mesh))
         (tex-coords (mesh-tex-coords mesh))
         (dims       (mesh-dimensions mesh))
         (v-count    (vertex-count mesh))
         (t-count    (triangle-count mesh))
         (has-n      (not (null normals)))
         (has-uv     (not (null tex-coords))))
    (ensure-directories-exist filepath)
    (with-open-file (out filepath :direction :output
                                  :if-exists :supersede
                                  :if-does-not-exist :create)
      (format out "# Generated by common-shapes~%# Vertices: ~D  Triangles: ~D~%~%" v-count t-count)
      ;; Vertex positions — always emit 3 components (z=0.0 for 2D)
      (dotimes (i v-count)
        (if (= dims 3)
            (let ((b (* i 3)))
              (format out "v ~,6F ~,6F ~,6F~%" (aref vertices b) (aref vertices (+ b 1)) (aref vertices (+ b 2))))
            (let ((b (* i 2)))
              (format out "v ~,6F ~,6F 0.000000~%" (aref vertices b) (aref vertices (+ b 1))))))
      ;; Texture coordinates
      (when has-uv
        (dotimes (i v-count)
          (let ((b (* i 2)))
            (format out "vt ~,6F ~,6F~%" (aref tex-coords b) (aref tex-coords (+ b 1))))))
      ;; Normals
      (when has-n
        (dotimes (i v-count)
          (let ((b (* i 3)))
            (format out "vn ~,6F ~,6F ~,6F~%" (aref normals b) (aref normals (+ b 1)) (aref normals (+ b 2))))))
      ;; Faces (1-indexed)
      (dotimes (tri t-count)
        (let* ((b  (* tri 3))
               (i0 (1+ (aref indices b)))
               (i1 (1+ (aref indices (+ b 1))))
               (i2 (1+ (aref indices (+ b 2)))))
          (cond
            ((and has-uv has-n)
             (format out "f ~D/~D/~D ~D/~D/~D ~D/~D/~D~%" i0 i0 i0 i1 i1 i1 i2 i2 i2))
            (has-uv
             (format out "f ~D/~D ~D/~D ~D/~D~%" i0 i0 i1 i1 i2 i2))
            (has-n
             (format out "f ~D//~D ~D//~D ~D//~D~%" i0 i0 i1 i1 i2 i2))
            (t
             (format out "f ~D ~D ~D~%" i0 i1 i2))))))
    t))

;;;; Sanity helper (unchanged)

(defun check-mesh (mesh &key normals tex-coords)
  (and (not (null (mesh-vertices mesh)))
       (not (null (mesh-indices mesh)))
       (> (vertex-count mesh) 0)
       (> (triangle-count mesh) 0)
       (if normals    (not (null (mesh-normals mesh)))    t)
       (if tex-coords (not (null (mesh-tex-coords mesh))) t)))

;;;; Macro to generate the repetitive shape tests

(defmacro define-shape-test (name (constructor &rest base-args)
                             &key
                             (base-checks nil)
                             (extra-variants nil))
  "Define a FiveAM test for a shape constructor.
NAME         – symbol naming the test (also used to build output filenames)
CONSTRUCTOR  – function that creates the mesh (e.g. make-rectangle-2d)
BASE-ARGS    – required arguments for the constructor (without keyword options)
BASE-CHECKS  – list of assertions to run on the basic mesh (e.g. ((= 4 (vertex-count mesh))))
EXTRA-VARIANTS – list of additional variants, each of the form
                 (SUFFIX EXTRA-ARGS EXTRA-CHECKS)
                 where EXTRA-ARGS are keyword arguments added to the constructor
                 and EXTRA-CHECKS are assertions specific to that variant.
The macro automatically adds:
- a basic variant (no normals/tex-coords)
- a full variant (:normals t :tex-coords t)
plus any user-supplied extra variants."
  (let ((basic-test
          `(let ((mesh (,constructor ,@base-args)))
             (is (check-mesh mesh))
             ,@(loop for check in base-checks collect `(is ,check))
             (is (write-mesh-to-obj mesh (output-path ',name)))))
        (full-test
          `(let ((mesh (,constructor ,@base-args :normals t :tex-coords t)))
             (is (check-mesh mesh :normals t :tex-coords t))
             (is (write-mesh-to-obj mesh (output-path ',name "full")))))
        (extra-forms
          (loop for (suffix extra-args extra-checks) in extra-variants
                collect
                `(let ((mesh (,constructor ,@base-args ,@extra-args)))
                   (is (check-mesh mesh
                                    ,@(when (find :normals extra-args) '(:normals t))
                                    ,@(when (find :tex-coords extra-args) '(:tex-coords t))))
                   ,@(loop for check in extra-checks collect `(is ,check))
                   (is (write-mesh-to-obj mesh (output-path ',name ,suffix)))))))
    `(test ,name
       ,basic-test
       ,full-test
       ,@extra-forms)))

;;;; Test suites

(def-suite common-shapes-suite
  :description "All common-shapes tests")

(def-suite* shapes-2d :in common-shapes-suite)

(define-shape-test rectangle-2d (make-rectangle-2d 2.0 1.0)
  :base-checks ((= 4 (vertex-count mesh))
                (= 2 (triangle-count mesh))))

(define-shape-test circle-2d (make-circle-2d 1.0 32))

(define-shape-test polygon-2d (make-polygon-2d 6 1.0)
  :base-checks ((= 7 (vertex-count mesh))
                (= 6 (triangle-count mesh))))

(define-shape-test ellipse-2d (make-ellipse-2d 2.0 1.0 32)
  :extra-variants (("3d" (:3d t) ((= 3 (mesh-dimensions mesh))))))

(def-suite* shapes-3d :in common-shapes-suite)

(define-shape-test cube (make-cube 1.0)
  :base-checks ((= 24 (vertex-count mesh))
                (= 12 (triangle-count mesh))))

(define-shape-test box (make-box 2.0 1.0 0.5))

(define-shape-test sphere (make-sphere 1.0 16 16))

(define-shape-test icosphere (make-icosphere 1.0 2))

(define-shape-test cylinder (make-cylinder 0.5 1.0 16 4))

(define-shape-test cone (make-cone 0.5 1.0 16 4))

(define-shape-test torus (make-torus 1.0 0.3 16 16))

(define-shape-test plane (make-plane 2.0 2.0 4 4))

(define-shape-test hemisphere (make-hemisphere 1.0 16 8))

(define-shape-test capsule (make-capsule 0.5 1.0 16 8))

;; merge-arrow is special – keep it explicit
(test merge-arrow
  ;; Shaft: cylinder centered at origin, translated up so base is at y=0, tip at y=1.5
  ;; Head:  cone with base at y=0, apex at y=0.5, translated up to sit at y=1.5
  (let* ((shaft (translate-mesh (make-cylinder 0.3 1.5 16 4) 0 0.75 0))
         (head  (translate-mesh (make-cone    0.6 0.5 16 1) 0 1.5  0))
         (arrow (merge-meshes shaft head)))
    (is (check-mesh arrow))
    (is (= (+ (vertex-count shaft) (vertex-count head))
           (vertex-count arrow)))
    (is (= (+ (triangle-count shaft) (triangle-count head))
           (triangle-count arrow)))
    (is (write-mesh-to-obj arrow (output-path 'arrow))))
  ;; Same with normals — merge only preserves them when both parts have them
  (let* ((shaft (translate-mesh (make-cylinder 0.3 1.5 16 4 :normals t) 0 0.75 0))
         (head  (translate-mesh (make-cone    0.6 0.5 16 1 :normals t) 0 1.5  0))
         (arrow (merge-meshes shaft head)))
    (is (check-mesh arrow :normals t))
    (is (write-mesh-to-obj arrow (output-path 'arrow "normals")))))

(def-suite* shapes-platonic :in common-shapes-suite)

(define-shape-test tetrahedron (make-tetrahedron 1.0)
  :base-checks ((= 12 (vertex-count mesh))
                (= 4 (triangle-count mesh))))

(define-shape-test octahedron (make-octahedron 1.0)
  :base-checks ((= 24 (vertex-count mesh))
                (= 8 (triangle-count mesh))))

(define-shape-test icosahedron (make-icosahedron 1.0)
  :base-checks ((= 60 (vertex-count mesh))
                (= 20 (triangle-count mesh))))

(define-shape-test dodecahedron (make-dodecahedron 1.0)
  :base-checks ((= 108 (vertex-count mesh))
                (= 36 (triangle-count mesh))))

(def-suite* math-suite :in common-shapes-suite)

(test vec-ops
  (let ((u (common-shapes:vec3 1.0 0.0 0.0))
        (w (common-shapes:vec3 0.0 1.0 0.0)))
    ;; vunit: unit length, zero-vector guard
    (let ((n (v:vunit (common-shapes:vec3 3.0 4.0 0.0))))
      (is (< (abs (- 1.0 (sqrt (+ (* (v:vx3 n) (v:vx3 n))
                                  (* (v:vy3 n) (v:vy3 n))
                                  (* (v:vz3 n) (v:vz3 n))))))
             1e-5)))
    (let ((z (v:vunit (common-shapes:vec3 0.0 0.0 0.0))))
      (is (= 0.0 (v:vx3 z) (v:vy3 z) (v:vz3 z))))
    ;; vc: right-hand rule, x cross y = z
    (let ((c (v:vc u w)))
      (is (< (abs (- 1.0 (v:vz3 c))) 1e-5))
      (is (< (abs (v:vx3 c)) 1e-5))
      (is (< (abs (v:vy3 c)) 1e-5)))
    ;; v+ / v- / v* componentwise
    (let ((s (v:v+ u w)))
      (is (= 1.0 (v:vx3 s))) (is (= 1.0 (v:vy3 s))) (is (= 0.0 (v:vz3 s))))
    (let ((d (v:v- u w)))
      (is (= 1.0 (v:vx3 d))) (is (= -1.0 (v:vy3 d))) (is (= 0.0 (v:vz3 d))))
    (let ((m (v:v* u 2.0)))
      (is (= 2.0 (v:vx3 m))) (is (= 0.0 (v:vy3 m))) (is (= 0.0 (v:vz3 m))))))

(defun approx= (a b &optional (eps 1e-4))
  (< (abs (- a b)) eps))

(test mat-ops
  (let ((p (common-shapes:vec3 1.0 0.0 0.0)))
    ;; mtranslation
    (let* ((tm (common-shapes:mtranslation (common-shapes:vec3 2.0 3.0 4.0)))
           (tp (m:m* tm p)))
      (is (approx= 3.0 (v:vx3 tp)))
      (is (approx= 3.0 (v:vy3 tp)))
      (is (approx= 4.0 (v:vz3 tp))))
    ;; mscaling
    (let* ((sm (m:mscaling (common-shapes:vec3 2.0 3.0 4.0)))
           (sp (m:m* sm p)))
      (is (approx= 2.0 (v:vx3 sp))))
    ;; mrotation about Z by pi/2: (1,0,0) -> (0,1,0)
    (let* ((rm (common-shapes:mrotation (common-shapes:vec3 0.0 0.0 1.0) (/ pi 2)))
           (rp (m:m* rm p)))
      (is (approx= 0.0 (v:vx3 rp)))
      (is (approx= 1.0 (v:vy3 rp)))
      (is (approx= 0.0 (v:vz3 rp))))
    ;; minv: M^-1 * (M * p) = p, for rotation, translation, and scaling
    (dolist (mtx (list (common-shapes:mrotation (common-shapes:vec3 0.0 1.0 0.0) 0.7)
                        (common-shapes:mtranslation (common-shapes:vec3 2.0 -3.0 4.0))
                        (common-shapes:mscaling (common-shapes:vec3 2.0 3.0 4.0))
                        (m:m* (common-shapes:mtranslation (common-shapes:vec3 2.0 -3.0 4.0))
                              (common-shapes:mrotation (common-shapes:vec3 0.0 1.0 0.0) 0.7))))
      (let* ((im (m:minv mtx))
             (mp (m:m* mtx p))
             (back (m:m* im mp)))
        (is (approx= (v:vx3 p) (v:vx3 back)))
        (is (approx= (v:vy3 p) (v:vy3 back)))
        (is (approx= (v:vz3 p) (v:vz3 back)))))
    ;; mtranspose is an involution
    (let* ((tm (common-shapes:mtranslation (common-shapes:vec3 2.0 3.0 4.0)))
           (tt (m:mtranspose (m:mtranspose tm)))
           (arr1 (m:marr tm))
           (arr2 (m:marr tt)))
      (is (every #'approx= arr1 arr2)))
    ;; m* composition: (T * R) applied to p equals T applied to (R applied to p)
    (let* ((tm (common-shapes:mtranslation (common-shapes:vec3 5.0 0.0 0.0)))
           (rm (common-shapes:mrotation (common-shapes:vec3 0.0 0.0 1.0) (/ pi 2)))
           (composed (m:m* tm rm))
           (via-compose (m:m* composed p))
           (via-steps (m:m* tm (m:m* rm p))))
      (is (approx= (v:vx3 via-compose) (v:vx3 via-steps)))
      (is (approx= (v:vy3 via-compose) (v:vy3 via-steps)))
      (is (approx= (v:vz3 via-compose) (v:vz3 via-steps))))))

(test mat-layout
  (let ((tm (common-shapes:mtranslation (common-shapes:vec3 1.0 2.0 3.0))))
    (let ((col (m:marr tm :column-major))
          (row (m:marr tm :row-major)))
      ;; column-major: translation at indices 12/13/14
      (is (approx= 1.0 (aref col 12)))
      (is (approx= 2.0 (aref col 13)))
      (is (approx= 3.0 (aref col 14)))
      ;; row-major: translation at indices 3/7/11 (the transpose)
      (is (approx= 1.0 (aref row 3)))
      (is (approx= 2.0 (aref row 7)))
      (is (approx= 3.0 (aref row 11)))
      ;; the two layouts are element-wise transposes of one another
      (dotimes (r 4)
        (dotimes (c 4)
          (is (approx= (aref col (+ (* c 4) r)) (aref row (+ (* r 4) c))))))
      ;; round-trip: mat4-from-array of (marr m layout) in the same layout
      ;; reconstructs the original matrix, for both layouts
      (let ((rt-col (m:mat4-from-array col :column-major))
            (rt-row (m:mat4-from-array row :row-major)))
        (is (every #'approx= col (m:marr rt-col :column-major)))
        (is (every #'approx= row (m:marr rt-row :row-major)))))))

;;;; Entrypoint

(def-suite* csg :in common-shapes-suite)

(test csg-union-test
  (let* ((a (make-cube 1.0))
         (b (translate-mesh (make-cube 1.0) 0.5 0.0 0.0))
         (result (csg-union a b)))
    (is (check-mesh result))
    (is (= 3 (mesh-dimensions result)))
    (is (write-mesh-to-obj result (output-path 'csg-union)))))

(test csg-intersection-test
  (let* ((a (make-cube 1.0))
         (b (translate-mesh (make-cube 1.0) 0.5 0.0 0.0))
         (result (csg-intersection a b)))
    (is (check-mesh result))
    (is (= 3 (mesh-dimensions result)))
    (is (write-mesh-to-obj result (output-path 'csg-intersection)))))

(test csg-difference-test
  (let* ((a (make-cube 1.0))
         (b (translate-mesh (make-cube 1.0) 0.5 0.0 0.0))
         (result (csg-difference a b)))
    (is (check-mesh result))
    (is (= 3 (mesh-dimensions result)))
    (is (write-mesh-to-obj result (output-path 'csg-difference)))))

(test csg-sphere-intersection
  (let* ((a (make-sphere 1.0 16 12))
         (b (translate-mesh (make-sphere 1.0 16 12) 0.5 0.0 0.0))
         (result (csg-intersection a b)))
    (is (check-mesh result))
    (is (write-mesh-to-obj result (output-path 'csg-sphere-intersection)))))

(test csg-cylinder-difference
  (let* ((a (make-cube 2.0))
         (b (make-cylinder 0.5 2.0 16 4))
         (result (csg-difference a b)))
    (is (check-mesh result))
    (is (write-mesh-to-obj result (output-path 'csg-cylinder-difference)))))

(defun run-tests ()
  (run! 'common-shapes-suite))
